### ISSUE TITLE
Accessing profile page without authentication

### ISSUE THREAD

**Issue by Tubaleviao** [Tubaleviao/tuba.work#10]
When I try to access the profile page (https://tuba.work/profile), the application throws an error and stop running:

```
8|tuba.work  | TypeError: Cannot read property 'date' of null
8|tuba.work  |     at users.findOne (/home/tuba/nodejs/tuba.work/mongo.js:88:41)
8|tuba.work  |     at result (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
8|tuba.work  |     at session.endSession (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
8|tuba.work  |     at ClientSession.endSession (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/core/sessions.js:135:41)
8|tuba.work  |     at executeCallback (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
8|tuba.work  |     at handleCallback (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/utils.js:129:55)
8|tuba.work  |     at cursor.next (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/operations/find_one.js:28:7)
8|tuba.work  |     at result (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
8|tuba.work  |     at executeCallback (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
8|tuba.work  |     at handleCallback (/home/tuba/nodejs/tuba.work/node_modules/mongodb/lib/utils.js:129:55)
```

**Comment by tyeshi181** [comment]
i will look into it.
